### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by thomasf1** [Climenty/svg-join#2]
Even just running 'svg-join' without parameters gives me the following error:

```javascript
Thomass-MacBook-Pro:o2 tom$ svg-join 
/usr/local/lib/node_modules/svg-join/svg-join.js:14
const parseUnit = (value = '') => value.replace(/[\d.\s]/g, '')
                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-join/bin/svg-join:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

The node version I´m running is v4.6.2

Any idea what´s going on? Some Node version issue?

**Comment by Climenty** [comment]
Yes, version issue.
[http://node.green/#default-function-parameters](http://node.green/#default-function-parameters)
Looks like your node does not support default function parameters or ES2015 syntax at all.

**Comment by thomasf1** [comment]
Right... A requires node xx+ in as a error or in the readme would be great :)
